dream_community_website_accueil:
    pattern:  /{page}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:index, page: 1 }
    requirements:
        id:  \d+
dream_community_website_article:
    pattern:  /article/{id}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:article }
    requirements:
        id:  \d+
dream_community_website_membres:
    pattern:  /membres
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:membres }
dream_community_website_membre:
    pattern:  /membre/{id}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:membre }
    requirements:
        id:  \d+

dream_community_website_membre_videos:
    pattern:  /membre/{id}/videos
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:membreVideos }
    requirements:
        id:  \d+
dream_community_website_videos:
    pattern:  /videos/{page}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:videos, page: 1 }
    requirements:
        page:  \d+
dream_community_website_video:
    pattern:  /video/{id}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:video }
    requirements:
        id:  \d+

dream_community_website_forum:
    pattern:  /forum
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:forum }
dream_community_website_contacts:
    pattern:  /contacts
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:contacts }
dream_community_website_liens:
    pattern:  /liens
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:liens }

dream_community_website_ajout_video:
    pattern:  /video/ajouter
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:ajoutVideo }
dream_community_website_modif_video:
    pattern:  /video/modifier/{id}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:modifVideo }
    requirements:
        id:  \d+
dream_community_website_supprim_video:
    pattern:  /video/supprime/{id}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:supprimVideo }
    requirements:
        id:  \d+

dream_community_website_vue_profil:
    pattern:  /monprofil
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:vueProfil }
dream_community_website_modif_profil:
    pattern:  /monprofil/modifier
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:modifierProfil }

dream_community_website_mes_videos:
    pattern:  /monprofil/videos
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:mesVideos }


dream_community_website_ajout_membre:
    pattern:  /membres/ajout
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:ajoutMembre }
dream_community_website_modif_membre:
    pattern:  /membres/modif/{id}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:modifMembre }
    requirements:
        id:  \d+

dream_community_website_ajout_article:
    pattern:  /articles/ajout/
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:ajoutArticle }
dream_community_website_modif_article:
    pattern:  /articles/modif/{id}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:modifArticle }
    requirements:
        id:  \d+
dream_community_website_supprim_article:
    pattern:  /articles/supprimer/{id}
    defaults: { _controller: DreamCommunityWebsiteBundle:Website:supprimArticle }
    requirements:
        id:  \d+