parameters:
#    dream_community_website.example.class: DreamCommunity\WebsiteBundle\Example

services:
#    dream_community_website.example:
#        class: %dream_community_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
