<?php

namespace DreamCommunity\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleFunctionRepository extends EntityRepository
{
}
